// Référentiel canonique des pays (ISO 3166-1 alpha-2) pour imposer le choix
// à la création d'un pays dans le back-office : pas de faute de frappe sur le nom,
// code et devise pré-renseignés. `cont` mappe vers le ContinentCode du backend.
export type ContinentCode = "EUROPE" | "AFRIQUE" | "ASIE" | "AMERIQUE_NORD" | "AMERIQUE_SUD" | "OCEANIE";

export interface CountryRef {
  code: string; // ISO alpha-2
  fr: string;
  en: string;
  cur: string; // ISO 4217
  cont: ContinentCode;
}

export const COUNTRIES: CountryRef[] = [
  // ---- AFRIQUE ----
  { code: "DZ", fr: "Algérie", en: "Algeria", cur: "DZD", cont: "AFRIQUE" },
  { code: "AO", fr: "Angola", en: "Angola", cur: "AOA", cont: "AFRIQUE" },
  { code: "BJ", fr: "Bénin", en: "Benin", cur: "XOF", cont: "AFRIQUE" },
  { code: "BW", fr: "Botswana", en: "Botswana", cur: "BWP", cont: "AFRIQUE" },
  { code: "BF", fr: "Burkina Faso", en: "Burkina Faso", cur: "XOF", cont: "AFRIQUE" },
  { code: "BI", fr: "Burundi", en: "Burundi", cur: "BIF", cont: "AFRIQUE" },
  { code: "CM", fr: "Cameroun", en: "Cameroon", cur: "XAF", cont: "AFRIQUE" },
  { code: "CV", fr: "Cap-Vert", en: "Cape Verde", cur: "CVE", cont: "AFRIQUE" },
  { code: "CF", fr: "République centrafricaine", en: "Central African Republic", cur: "XAF", cont: "AFRIQUE" },
  { code: "TD", fr: "Tchad", en: "Chad", cur: "XAF", cont: "AFRIQUE" },
  { code: "KM", fr: "Comores", en: "Comoros", cur: "KMF", cont: "AFRIQUE" },
  { code: "CG", fr: "Congo", en: "Congo", cur: "XAF", cont: "AFRIQUE" },
  { code: "CD", fr: "République démocratique du Congo", en: "DR Congo", cur: "CDF", cont: "AFRIQUE" },
  { code: "CI", fr: "Côte d'Ivoire", en: "Ivory Coast", cur: "XOF", cont: "AFRIQUE" },
  { code: "DJ", fr: "Djibouti", en: "Djibouti", cur: "DJF", cont: "AFRIQUE" },
  { code: "EG", fr: "Égypte", en: "Egypt", cur: "EGP", cont: "AFRIQUE" },
  { code: "GQ", fr: "Guinée équatoriale", en: "Equatorial Guinea", cur: "XAF", cont: "AFRIQUE" },
  { code: "ER", fr: "Érythrée", en: "Eritrea", cur: "ERN", cont: "AFRIQUE" },
  { code: "SZ", fr: "Eswatini", en: "Eswatini", cur: "SZL", cont: "AFRIQUE" },
  { code: "ET", fr: "Éthiopie", en: "Ethiopia", cur: "ETB", cont: "AFRIQUE" },
  { code: "GA", fr: "Gabon", en: "Gabon", cur: "XAF", cont: "AFRIQUE" },
  { code: "GM", fr: "Gambie", en: "Gambia", cur: "GMD", cont: "AFRIQUE" },
  { code: "GH", fr: "Ghana", en: "Ghana", cur: "GHS", cont: "AFRIQUE" },
  { code: "GN", fr: "Guinée", en: "Guinea", cur: "GNF", cont: "AFRIQUE" },
  { code: "GW", fr: "Guinée-Bissau", en: "Guinea-Bissau", cur: "XOF", cont: "AFRIQUE" },
  { code: "KE", fr: "Kenya", en: "Kenya", cur: "KES", cont: "AFRIQUE" },
  { code: "LS", fr: "Lesotho", en: "Lesotho", cur: "LSL", cont: "AFRIQUE" },
  { code: "LR", fr: "Libéria", en: "Liberia", cur: "LRD", cont: "AFRIQUE" },
  { code: "LY", fr: "Libye", en: "Libya", cur: "LYD", cont: "AFRIQUE" },
  { code: "MG", fr: "Madagascar", en: "Madagascar", cur: "MGA", cont: "AFRIQUE" },
  { code: "MW", fr: "Malawi", en: "Malawi", cur: "MWK", cont: "AFRIQUE" },
  { code: "ML", fr: "Mali", en: "Mali", cur: "XOF", cont: "AFRIQUE" },
  { code: "MR", fr: "Mauritanie", en: "Mauritania", cur: "MRU", cont: "AFRIQUE" },
  { code: "MU", fr: "Maurice", en: "Mauritius", cur: "MUR", cont: "AFRIQUE" },
  { code: "MA", fr: "Maroc", en: "Morocco", cur: "MAD", cont: "AFRIQUE" },
  { code: "MZ", fr: "Mozambique", en: "Mozambique", cur: "MZN", cont: "AFRIQUE" },
  { code: "NA", fr: "Namibie", en: "Namibia", cur: "NAD", cont: "AFRIQUE" },
  { code: "NE", fr: "Niger", en: "Niger", cur: "XOF", cont: "AFRIQUE" },
  { code: "NG", fr: "Nigéria", en: "Nigeria", cur: "NGN", cont: "AFRIQUE" },
  { code: "RW", fr: "Rwanda", en: "Rwanda", cur: "RWF", cont: "AFRIQUE" },
  { code: "ST", fr: "Sao Tomé-et-Principe", en: "Sao Tome and Principe", cur: "STN", cont: "AFRIQUE" },
  { code: "SN", fr: "Sénégal", en: "Senegal", cur: "XOF", cont: "AFRIQUE" },
  { code: "SC", fr: "Seychelles", en: "Seychelles", cur: "SCR", cont: "AFRIQUE" },
  { code: "SL", fr: "Sierra Leone", en: "Sierra Leone", cur: "SLE", cont: "AFRIQUE" },
  { code: "SO", fr: "Somalie", en: "Somalia", cur: "SOS", cont: "AFRIQUE" },
  { code: "ZA", fr: "Afrique du Sud", en: "South Africa", cur: "ZAR", cont: "AFRIQUE" },
  { code: "SS", fr: "Soudan du Sud", en: "South Sudan", cur: "SSP", cont: "AFRIQUE" },
  { code: "SD", fr: "Soudan", en: "Sudan", cur: "SDG", cont: "AFRIQUE" },
  { code: "TZ", fr: "Tanzanie", en: "Tanzania", cur: "TZS", cont: "AFRIQUE" },
  { code: "TG", fr: "Togo", en: "Togo", cur: "XOF", cont: "AFRIQUE" },
  { code: "TN", fr: "Tunisie", en: "Tunisia", cur: "TND", cont: "AFRIQUE" },
  { code: "UG", fr: "Ouganda", en: "Uganda", cur: "UGX", cont: "AFRIQUE" },
  { code: "ZM", fr: "Zambie", en: "Zambia", cur: "ZMW", cont: "AFRIQUE" },
  { code: "ZW", fr: "Zimbabwe", en: "Zimbabwe", cur: "ZWL", cont: "AFRIQUE" },

  // ---- EUROPE ----
  { code: "AL", fr: "Albanie", en: "Albania", cur: "ALL", cont: "EUROPE" },
  { code: "AD", fr: "Andorre", en: "Andorra", cur: "EUR", cont: "EUROPE" },
  { code: "AT", fr: "Autriche", en: "Austria", cur: "EUR", cont: "EUROPE" },
  { code: "BY", fr: "Biélorussie", en: "Belarus", cur: "BYN", cont: "EUROPE" },
  { code: "BE", fr: "Belgique", en: "Belgium", cur: "EUR", cont: "EUROPE" },
  { code: "BA", fr: "Bosnie-Herzégovine", en: "Bosnia and Herzegovina", cur: "BAM", cont: "EUROPE" },
  { code: "BG", fr: "Bulgarie", en: "Bulgaria", cur: "BGN", cont: "EUROPE" },
  { code: "HR", fr: "Croatie", en: "Croatia", cur: "EUR", cont: "EUROPE" },
  { code: "CY", fr: "Chypre", en: "Cyprus", cur: "EUR", cont: "EUROPE" },
  { code: "CZ", fr: "Tchéquie", en: "Czechia", cur: "CZK", cont: "EUROPE" },
  { code: "DK", fr: "Danemark", en: "Denmark", cur: "DKK", cont: "EUROPE" },
  { code: "EE", fr: "Estonie", en: "Estonia", cur: "EUR", cont: "EUROPE" },
  { code: "FI", fr: "Finlande", en: "Finland", cur: "EUR", cont: "EUROPE" },
  { code: "FR", fr: "France", en: "France", cur: "EUR", cont: "EUROPE" },
  { code: "DE", fr: "Allemagne", en: "Germany", cur: "EUR", cont: "EUROPE" },
  { code: "GR", fr: "Grèce", en: "Greece", cur: "EUR", cont: "EUROPE" },
  { code: "HU", fr: "Hongrie", en: "Hungary", cur: "HUF", cont: "EUROPE" },
  { code: "IS", fr: "Islande", en: "Iceland", cur: "ISK", cont: "EUROPE" },
  { code: "IE", fr: "Irlande", en: "Ireland", cur: "EUR", cont: "EUROPE" },
  { code: "IT", fr: "Italie", en: "Italy", cur: "EUR", cont: "EUROPE" },
  { code: "XK", fr: "Kosovo", en: "Kosovo", cur: "EUR", cont: "EUROPE" },
  { code: "LV", fr: "Lettonie", en: "Latvia", cur: "EUR", cont: "EUROPE" },
  { code: "LI", fr: "Liechtenstein", en: "Liechtenstein", cur: "CHF", cont: "EUROPE" },
  { code: "LT", fr: "Lituanie", en: "Lithuania", cur: "EUR", cont: "EUROPE" },
  { code: "LU", fr: "Luxembourg", en: "Luxembourg", cur: "EUR", cont: "EUROPE" },
  { code: "MT", fr: "Malte", en: "Malta", cur: "EUR", cont: "EUROPE" },
  { code: "MD", fr: "Moldavie", en: "Moldova", cur: "MDL", cont: "EUROPE" },
  { code: "MC", fr: "Monaco", en: "Monaco", cur: "EUR", cont: "EUROPE" },
  { code: "ME", fr: "Monténégro", en: "Montenegro", cur: "EUR", cont: "EUROPE" },
  { code: "NL", fr: "Pays-Bas", en: "Netherlands", cur: "EUR", cont: "EUROPE" },
  { code: "MK", fr: "Macédoine du Nord", en: "North Macedonia", cur: "MKD", cont: "EUROPE" },
  { code: "NO", fr: "Norvège", en: "Norway", cur: "NOK", cont: "EUROPE" },
  { code: "PL", fr: "Pologne", en: "Poland", cur: "PLN", cont: "EUROPE" },
  { code: "PT", fr: "Portugal", en: "Portugal", cur: "EUR", cont: "EUROPE" },
  { code: "RO", fr: "Roumanie", en: "Romania", cur: "RON", cont: "EUROPE" },
  { code: "RU", fr: "Russie", en: "Russia", cur: "RUB", cont: "EUROPE" },
  { code: "SM", fr: "Saint-Marin", en: "San Marino", cur: "EUR", cont: "EUROPE" },
  { code: "RS", fr: "Serbie", en: "Serbia", cur: "RSD", cont: "EUROPE" },
  { code: "SK", fr: "Slovaquie", en: "Slovakia", cur: "EUR", cont: "EUROPE" },
  { code: "SI", fr: "Slovénie", en: "Slovenia", cur: "EUR", cont: "EUROPE" },
  { code: "ES", fr: "Espagne", en: "Spain", cur: "EUR", cont: "EUROPE" },
  { code: "SE", fr: "Suède", en: "Sweden", cur: "SEK", cont: "EUROPE" },
  { code: "CH", fr: "Suisse", en: "Switzerland", cur: "CHF", cont: "EUROPE" },
  { code: "UA", fr: "Ukraine", en: "Ukraine", cur: "UAH", cont: "EUROPE" },
  { code: "GB", fr: "Royaume-Uni", en: "United Kingdom", cur: "GBP", cont: "EUROPE" },
  { code: "VA", fr: "Vatican", en: "Vatican City", cur: "EUR", cont: "EUROPE" },

  // ---- ASIE ----
  { code: "AF", fr: "Afghanistan", en: "Afghanistan", cur: "AFN", cont: "ASIE" },
  { code: "AM", fr: "Arménie", en: "Armenia", cur: "AMD", cont: "ASIE" },
  { code: "AZ", fr: "Azerbaïdjan", en: "Azerbaijan", cur: "AZN", cont: "ASIE" },
  { code: "BH", fr: "Bahreïn", en: "Bahrain", cur: "BHD", cont: "ASIE" },
  { code: "BD", fr: "Bangladesh", en: "Bangladesh", cur: "BDT", cont: "ASIE" },
  { code: "BT", fr: "Bhoutan", en: "Bhutan", cur: "BTN", cont: "ASIE" },
  { code: "BN", fr: "Brunéi", en: "Brunei", cur: "BND", cont: "ASIE" },
  { code: "KH", fr: "Cambodge", en: "Cambodia", cur: "KHR", cont: "ASIE" },
  { code: "CN", fr: "Chine", en: "China", cur: "CNY", cont: "ASIE" },
  { code: "GE", fr: "Géorgie", en: "Georgia", cur: "GEL", cont: "ASIE" },
  { code: "IN", fr: "Inde", en: "India", cur: "INR", cont: "ASIE" },
  { code: "ID", fr: "Indonésie", en: "Indonesia", cur: "IDR", cont: "ASIE" },
  { code: "IR", fr: "Iran", en: "Iran", cur: "IRR", cont: "ASIE" },
  { code: "IQ", fr: "Irak", en: "Iraq", cur: "IQD", cont: "ASIE" },
  { code: "IL", fr: "Israël", en: "Israel", cur: "ILS", cont: "ASIE" },
  { code: "JP", fr: "Japon", en: "Japan", cur: "JPY", cont: "ASIE" },
  { code: "JO", fr: "Jordanie", en: "Jordan", cur: "JOD", cont: "ASIE" },
  { code: "KZ", fr: "Kazakhstan", en: "Kazakhstan", cur: "KZT", cont: "ASIE" },
  { code: "KW", fr: "Koweït", en: "Kuwait", cur: "KWD", cont: "ASIE" },
  { code: "KG", fr: "Kirghizistan", en: "Kyrgyzstan", cur: "KGS", cont: "ASIE" },
  { code: "LA", fr: "Laos", en: "Laos", cur: "LAK", cont: "ASIE" },
  { code: "LB", fr: "Liban", en: "Lebanon", cur: "LBP", cont: "ASIE" },
  { code: "MY", fr: "Malaisie", en: "Malaysia", cur: "MYR", cont: "ASIE" },
  { code: "MV", fr: "Maldives", en: "Maldives", cur: "MVR", cont: "ASIE" },
  { code: "MN", fr: "Mongolie", en: "Mongolia", cur: "MNT", cont: "ASIE" },
  { code: "MM", fr: "Birmanie", en: "Myanmar", cur: "MMK", cont: "ASIE" },
  { code: "NP", fr: "Népal", en: "Nepal", cur: "NPR", cont: "ASIE" },
  { code: "KP", fr: "Corée du Nord", en: "North Korea", cur: "KPW", cont: "ASIE" },
  { code: "OM", fr: "Oman", en: "Oman", cur: "OMR", cont: "ASIE" },
  { code: "PK", fr: "Pakistan", en: "Pakistan", cur: "PKR", cont: "ASIE" },
  { code: "PS", fr: "Palestine", en: "Palestine", cur: "ILS", cont: "ASIE" },
  { code: "PH", fr: "Philippines", en: "Philippines", cur: "PHP", cont: "ASIE" },
  { code: "QA", fr: "Qatar", en: "Qatar", cur: "QAR", cont: "ASIE" },
  { code: "SA", fr: "Arabie saoudite", en: "Saudi Arabia", cur: "SAR", cont: "ASIE" },
  { code: "SG", fr: "Singapour", en: "Singapore", cur: "SGD", cont: "ASIE" },
  { code: "KR", fr: "Corée du Sud", en: "South Korea", cur: "KRW", cont: "ASIE" },
  { code: "LK", fr: "Sri Lanka", en: "Sri Lanka", cur: "LKR", cont: "ASIE" },
  { code: "SY", fr: "Syrie", en: "Syria", cur: "SYP", cont: "ASIE" },
  { code: "TW", fr: "Taïwan", en: "Taiwan", cur: "TWD", cont: "ASIE" },
  { code: "TJ", fr: "Tadjikistan", en: "Tajikistan", cur: "TJS", cont: "ASIE" },
  { code: "TH", fr: "Thaïlande", en: "Thailand", cur: "THB", cont: "ASIE" },
  { code: "TL", fr: "Timor oriental", en: "Timor-Leste", cur: "USD", cont: "ASIE" },
  { code: "TR", fr: "Turquie", en: "Turkey", cur: "TRY", cont: "ASIE" },
  { code: "TM", fr: "Turkménistan", en: "Turkmenistan", cur: "TMT", cont: "ASIE" },
  { code: "AE", fr: "Émirats arabes unis", en: "United Arab Emirates", cur: "AED", cont: "ASIE" },
  { code: "UZ", fr: "Ouzbékistan", en: "Uzbekistan", cur: "UZS", cont: "ASIE" },
  { code: "VN", fr: "Viêt Nam", en: "Vietnam", cur: "VND", cont: "ASIE" },
  { code: "YE", fr: "Yémen", en: "Yemen", cur: "YER", cont: "ASIE" },

  // ---- AMÉRIQUE DU NORD & CENTRALE / CARAÏBES ----
  { code: "AG", fr: "Antigua-et-Barbuda", en: "Antigua and Barbuda", cur: "XCD", cont: "AMERIQUE_NORD" },
  { code: "BS", fr: "Bahamas", en: "Bahamas", cur: "BSD", cont: "AMERIQUE_NORD" },
  { code: "BB", fr: "Barbade", en: "Barbados", cur: "BBD", cont: "AMERIQUE_NORD" },
  { code: "BZ", fr: "Belize", en: "Belize", cur: "BZD", cont: "AMERIQUE_NORD" },
  { code: "CA", fr: "Canada", en: "Canada", cur: "CAD", cont: "AMERIQUE_NORD" },
  { code: "CR", fr: "Costa Rica", en: "Costa Rica", cur: "CRC", cont: "AMERIQUE_NORD" },
  { code: "CU", fr: "Cuba", en: "Cuba", cur: "CUP", cont: "AMERIQUE_NORD" },
  { code: "DM", fr: "Dominique", en: "Dominica", cur: "XCD", cont: "AMERIQUE_NORD" },
  { code: "DO", fr: "République dominicaine", en: "Dominican Republic", cur: "DOP", cont: "AMERIQUE_NORD" },
  { code: "SV", fr: "Salvador", en: "El Salvador", cur: "USD", cont: "AMERIQUE_NORD" },
  { code: "GD", fr: "Grenade", en: "Grenada", cur: "XCD", cont: "AMERIQUE_NORD" },
  { code: "GT", fr: "Guatemala", en: "Guatemala", cur: "GTQ", cont: "AMERIQUE_NORD" },
  { code: "HT", fr: "Haïti", en: "Haiti", cur: "HTG", cont: "AMERIQUE_NORD" },
  { code: "HN", fr: "Honduras", en: "Honduras", cur: "HNL", cont: "AMERIQUE_NORD" },
  { code: "JM", fr: "Jamaïque", en: "Jamaica", cur: "JMD", cont: "AMERIQUE_NORD" },
  { code: "MX", fr: "Mexique", en: "Mexico", cur: "MXN", cont: "AMERIQUE_NORD" },
  { code: "NI", fr: "Nicaragua", en: "Nicaragua", cur: "NIO", cont: "AMERIQUE_NORD" },
  { code: "PA", fr: "Panama", en: "Panama", cur: "PAB", cont: "AMERIQUE_NORD" },
  { code: "KN", fr: "Saint-Kitts-et-Nevis", en: "Saint Kitts and Nevis", cur: "XCD", cont: "AMERIQUE_NORD" },
  { code: "LC", fr: "Sainte-Lucie", en: "Saint Lucia", cur: "XCD", cont: "AMERIQUE_NORD" },
  { code: "VC", fr: "Saint-Vincent-et-les-Grenadines", en: "Saint Vincent and the Grenadines", cur: "XCD", cont: "AMERIQUE_NORD" },
  { code: "TT", fr: "Trinité-et-Tobago", en: "Trinidad and Tobago", cur: "TTD", cont: "AMERIQUE_NORD" },
  { code: "US", fr: "États-Unis", en: "United States", cur: "USD", cont: "AMERIQUE_NORD" },

  // ---- AMÉRIQUE DU SUD ----
  { code: "AR", fr: "Argentine", en: "Argentina", cur: "ARS", cont: "AMERIQUE_SUD" },
  { code: "BO", fr: "Bolivie", en: "Bolivia", cur: "BOB", cont: "AMERIQUE_SUD" },
  { code: "BR", fr: "Brésil", en: "Brazil", cur: "BRL", cont: "AMERIQUE_SUD" },
  { code: "CL", fr: "Chili", en: "Chile", cur: "CLP", cont: "AMERIQUE_SUD" },
  { code: "CO", fr: "Colombie", en: "Colombia", cur: "COP", cont: "AMERIQUE_SUD" },
  { code: "EC", fr: "Équateur", en: "Ecuador", cur: "USD", cont: "AMERIQUE_SUD" },
  { code: "GY", fr: "Guyana", en: "Guyana", cur: "GYD", cont: "AMERIQUE_SUD" },
  { code: "PY", fr: "Paraguay", en: "Paraguay", cur: "PYG", cont: "AMERIQUE_SUD" },
  { code: "PE", fr: "Pérou", en: "Peru", cur: "PEN", cont: "AMERIQUE_SUD" },
  { code: "SR", fr: "Suriname", en: "Suriname", cur: "SRD", cont: "AMERIQUE_SUD" },
  { code: "UY", fr: "Uruguay", en: "Uruguay", cur: "UYU", cont: "AMERIQUE_SUD" },
  { code: "VE", fr: "Venezuela", en: "Venezuela", cur: "VES", cont: "AMERIQUE_SUD" },

  // ---- OCÉANIE ----
  { code: "AU", fr: "Australie", en: "Australia", cur: "AUD", cont: "OCEANIE" },
  { code: "FJ", fr: "Fidji", en: "Fiji", cur: "FJD", cont: "OCEANIE" },
  { code: "KI", fr: "Kiribati", en: "Kiribati", cur: "AUD", cont: "OCEANIE" },
  { code: "MH", fr: "Îles Marshall", en: "Marshall Islands", cur: "USD", cont: "OCEANIE" },
  { code: "FM", fr: "Micronésie", en: "Micronesia", cur: "USD", cont: "OCEANIE" },
  { code: "NR", fr: "Nauru", en: "Nauru", cur: "AUD", cont: "OCEANIE" },
  { code: "NZ", fr: "Nouvelle-Zélande", en: "New Zealand", cur: "NZD", cont: "OCEANIE" },
  { code: "PW", fr: "Palaos", en: "Palau", cur: "USD", cont: "OCEANIE" },
  { code: "PG", fr: "Papouasie-Nouvelle-Guinée", en: "Papua New Guinea", cur: "PGK", cont: "OCEANIE" },
  { code: "WS", fr: "Samoa", en: "Samoa", cur: "WST", cont: "OCEANIE" },
  { code: "SB", fr: "Îles Salomon", en: "Solomon Islands", cur: "SBD", cont: "OCEANIE" },
  { code: "TO", fr: "Tonga", en: "Tonga", cur: "TOP", cont: "OCEANIE" },
  { code: "TV", fr: "Tuvalu", en: "Tuvalu", cur: "AUD", cont: "OCEANIE" },
  { code: "VU", fr: "Vanuatu", en: "Vanuatu", cur: "VUV", cont: "OCEANIE" },
];

/** Pays triés par nom FR (pour les listes déroulantes). */
export const COUNTRIES_FR_SORTED: CountryRef[] = [...COUNTRIES].sort((a, b) => a.fr.localeCompare(b.fr, "fr"));
